#!C:\ProgramData\Anaconda3\python.exe
print("Content-Type:text/html\n\n")

import cgi
import pyodbc as db
import webbrowser as wb

val = cgi.FieldStorage()
username = val.getvalue("user_e")
password = val.getvalue("psrd_e")

con = db.connect(r'Driver={Microsoft Access Driver (*.mdb, *.accdb)};DBQ=C:\Users\Hari\Documents\compiler_user.accdb;')
cur = con.cursor()
cur.execute("SELECT u_name FROM users;")
nms=cur.fetchall()
con.close()

n=[]
for f in nms:
 n.append(f[0])

if username in n:
 con1 = db.connect(r'Driver={Microsoft Access Driver (*.mdb, *.accdb)};DBQ=C:\Users\Hari\Documents\compiler_user.accdb;')
 cur1 = con1.cursor()
 cur1.execute("SELECT password FROM users WHERE u_name='"+username+"';")
 a = cur1.fetchall()
 con1.close()
 if a[0][0]==password:
  print('''
<HTML><HEAD>
<TITLE>OnLangue-Compiler</TITLE>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="\main.css">
</HEAD>
<BODY class="body">
<div class="container-login100">
 <div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-54"><BR>
<H2 ALIGN="center">OnLangue</H2><BR>
 <P ALIGN="center"><BR>------- Hi <B>{}</B> Code here -------</P>
 <P ALIGN="center"><BR>But before you start we suggest reading the <A HREF="\Support.html" STYLE="color:white;">Instructions & Support</A> of OnLangue<BR></P><BR><BR>
 <FORM class="login100-form" ACTION="compiler_cgi" METHOD="POST">
  <div class="wrap-input100">Select Language :
      <SELECT NAME="language" class="input100" placeholder="Select Language">        
        <OPTION class="input100" SELECTED>Java</OPTION>
        <OPTION>Python</OPTION>
        <OPTION>HTML</OPTION>
        <OPTION>php</OPTION>
	<OPTION>c</OPTION>
	<OPTION>cpp</OPTION>
      </SELECT>
  </div><BR>
  <div class="wrap-input100">Filename without extension :
       <input class="input100" type="text" name="f_name" placeholder="Filename" required />
       <span class="focus-input100"></span>
  </div><BR>
  <div class="wrap-input100">Write Code Here<BR>
       <TEXTAREA NAME="code" ROWS="10" COLS="30" STYLE="font-size: 16px; background-color:#282828; color:#7FFF00;" REQUIRED></TEXTAREA>       
  </div><BR>
  <div class="wrap-input100">Parameters (if any) seperated by spaces :<BR>
       <input class="input100" type="text" name="parameters" placeholder="Give your filename without extension" value="none" required />
       <span class="focus-input100"></span>
  </div><BR>
  <div class="wrap-input100"><B>Note : </B>If there is no parameter then the filed must contain "none".</div>
   <INPUT TYPE="text" NAME="username" VALUE="{}" HIDDEN></INPUT>
     <div class="container-login100-form-btn"><BR>
       <div class="wrap-login100-form-btn">
        <div class="login100-form-bgbtn"></div>
         <button type="submit" class="login100-form-btn">COMPILE</button>
       </div><BR>
      </div>
<BR>
 </FORM>
</div>
</div>
  '''.format(username,username))
 else:
  print('<SCRIPT>window.alert("invalid password");window.history.back();</SCRIPT>')
else:
 print('<SCRIPT>window.alert("invalid username");window.history.back();</SCRIPT>')

print('</BODY></HTML>')